# Generated by Django 4.2.27 on 2026-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=50)),
                ('chat_date', models.DateTimeField(verbose_name='date chatted')),
                ('notes', models.TextField()),
            ],
        ),
    ]
